#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [[ "$#" -lt 3 ]] ; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit;
fi

FILE="$1" # $1 source file path
DESTINY="~"
IP="$2" # destiny server IP
USER="$3" # destiny username
KEY="$4" # SSH private key path

scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER"@"$IP":"$DESTINY"
