#!/usr/bin/env bash
# install nginx listening to port 80 and show string in the page.

apt-get update -y
apt-get upgrade -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html
