#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely.
function show()
{
	echo "I am invincible!!!"
}
trap show SIGTERM
while (( 1 )); do
		echo "To infinity and beyond"
		sleep 2
done
