#!/usr/bin/env bash
# loops from 1 to 10 and: displays different messages for each iteration
i=1
while [ $i -le 100 ]; do
	if (( i % 15 == 0 )); then
		echo "FizzBuzz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i++))
done
