#!/usr/bin/env bash
# loops from 1 to 10 and: displays different messages for each iteration
find . -maxdepth 1 -printf "%f\n" | cut -d " " -f1 | cut -d "-" -f2-
for ((i = 1; i <= 2; i++)); do
sleep 0.00001
done
