#!/usr/bin/env bash
# Create html and put it in the html directory
echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf
echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 restart
